//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderInfo
    {
        public int TID { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> orderDeliveryDate { get; set; }
        public string lcode { get; set; }
        public Nullable<System.DateTime> customerNotifiedByMsg { get; set; }
        public Nullable<System.DateTime> customerNotifiedByEmail { get; set; }
        public Nullable<int> orderTotalQty { get; set; }
        public Nullable<int> orderRecdTotalQty { get; set; }
        public string metalType { get; set; }
        public Nullable<decimal> metalRate { get; set; }
        public string remark { get; set; }
    }
}
