//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerM
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string CustName { get; set; }
        public string CustAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PAN { get; set; }
        public string CustType { get; set; }
    }
}
