//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOut
    {
        public int TID { get; set; }
        public int SeqNo { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string LCode { get; set; }
        public string PCode { get; set; }
        public string MetalType { get; set; }
        public string TType { get; set; }
        public Nullable<int> RefVNo { get; set; }
        public Nullable<decimal> Pcs { get; set; }
        public Nullable<decimal> GrossWt { get; set; }
        public Nullable<decimal> NetWt { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
