//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int TID { get; set; }
        public int orderNo { get; set; }
        public string LCode { get; set; }
        public string PCode { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string KID { get; set; }
        public Nullable<System.DateTime> artisanReqDate { get; set; }
        public Nullable<System.DateTime> orderPlacedDate { get; set; }
        public Nullable<System.DateTime> orderRecdDate { get; set; }
        public string orderType { get; set; }
        public Nullable<int> JobNo { get; set; }
        public Nullable<decimal> totalweight { get; set; }
    }
}
