//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SilverEntities : DbContext
    {
        public SilverEntities()
            : base("name=SilverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerM> CustomerMs { get; set; }
        public virtual DbSet<MetalM> MetalMs { get; set; }
        public virtual DbSet<ProductM> ProductMs { get; set; }
        public virtual DbSet<InOut> InOuts { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<StockInfo> StockInfoes { get; set; }
    }
}
